import { mkdir, writeFile } from "fs/promises";

export class ReportWriter {
    async write(
        experimentId: string,
        data: {
            experimentName: string;
            composition: string[];
            metrics: string[];
            benchmark: Record<string, unknown>;
            executedAt: string;
        }
    ): Promise<void> {
        await mkdir("./reports", { recursive: true });

        const markdown = [
            `# OECL Experiment Report`,
            ``,
            `## Experiment`,
            ``,
            `- ID: ${experimentId}`,
            `- Name: ${data.experimentName}`,
            `- Executed At: ${data.executedAt}`,
            ``,
            `## Composition`,
            ``,
            ...data.composition.map(protocol => `- ${protocol}`),
            ``,
            `## Metrics`,
            ``,
            ...data.metrics.map(metric => `- ${metric}`),
            ``,
            `## Benchmark`,
            ``,
            "```json",
            JSON.stringify(data.benchmark, null, 2),
            "```",
            ``,
            `## Status`,
            ``,
            `Report generated by OECL.`
        ].join("\n");

        await writeFile(
            `./reports/${experimentId}.md`,
            markdown,
            "utf8"
        );
    }
}