import type {
    ScientificJointContractHarnessRecipe
} from "../ScientificJointContractHarness.js";


export const ERC8004_CONTROL_REPOSITORY =
    "erc-8004/erc-8004-contracts";

export const ERC8060_CONTROL_REPOSITORY =
    "ten-io-meta/erc8060-native-eth-value";


export const ERC8004_CONTROL_REVISION =
    "b9e466c250744a7e06b13dff9d3c2844ed64f825";

export const ERC8060_CONTROL_REVISION =
    "c7eed906835ab39fbc8439eb0493e5a5371b23a2";


const DRIVER_SOURCE = String.raw`
import {
    readFile
} from "node:fs/promises";

import {
    join
} from "node:path";

import {
    network
} from "hardhat";

import {
    encodeAbiParameters,
    getContract,
    keccak256,
    toHex
} from "viem";


const participantARoot =
    process.env.OECL_PARTICIPANT_A_ROOT;

const participantBRoot =
    process.env.OECL_PARTICIPANT_B_ROOT;


if (
    !participantARoot ||
    !participantBRoot
) {

    throw new Error(
        "OECL bilateral participant roots are required."
    );

}


const requirementPath =
    process.env.OECL_COMPOSITION_EXECUTION_REQUIREMENT_PATH;


const requirement =
    requirementPath
        ? JSON.parse(
            await readFile(
                requirementPath,
                "utf8"
            )
        )
        : null;


const artifact8060Path =
    join(
        participantBRoot,
        "artifacts",
        "contracts",
        "ERC8060Reference.sol",
        "ERC8060Reference.json"
    );


const artifact8060 =
    JSON.parse(
        await readFile(
            artifact8060Path,
            "utf8"
        )
    );


const {
    viem
} =
    await network.connect();


const publicClient =
    await viem.getPublicClient();


const [
    owner
] =
    await viem.getWalletClients();


const chainId =
    await publicClient.getChainId();


const zeroAddress =
    "0x0000000000000000000000000000000000000000";


function encodeInitializeWithAddress(
    identityRegistry
) {

    const params =
        encodeAbiParameters(
            [
                {
                    type:
                        "address"
                }
            ],
            [
                identityRegistry
            ]
        );


    return (
        "0xc4d66de8" +
        params.slice(2)
    );

}


/*
 * Participant A:
 *
 * Preserve the exact deployment shape already exercised by the
 * ERC-8004 repository:
 *
 * HardhatMinimalUUPS
 * Ã¢â€ â€™ ERC1967Proxy
 * Ã¢â€ â€™ IdentityRegistryUpgradeable
 * Ã¢â€ â€™ upgradeToAndCall(initialize())
 */

const minimalImpl =
    await viem.deployContract(
        "HardhatMinimalUUPS"
    );


const proxy =
    await viem.deployContract(
        "ERC1967Proxy",
        [
            minimalImpl.address,
            encodeInitializeWithAddress(
                zeroAddress
            )
        ]
    );


const realImpl =
    await viem.deployContract(
        "IdentityRegistryUpgradeable"
    );


const minimalProxy =
    await viem.getContractAt(
        "HardhatMinimalUUPS",
        proxy.address
    );


await minimalProxy
    .write
    .upgradeToAndCall(
        [
            realImpl.address,
            "0x8129fc1c"
        ]
    );


const identityRegistry =
    await viem.getContractAt(
        "IdentityRegistryUpgradeable",
        proxy.address
    );


const uriA =
    "ipfs://oecl/control/erc8004-agent";


const txA =
    await identityRegistry
        .write
        .register(
            [
                uriA
            ]
        );


const receiptA =
    await publicClient
        .waitForTransactionReceipt(
            {
                hash:
                    txA
            }
        );


const registeredEventSignature =
    keccak256(
        toHex(
            "Registered(uint256,string,address)"
        )
    );


const registeredLog =
    receiptA.logs.find(
        log =>
            log.topics[0] ===
            registeredEventSignature
    );


if (
    !registeredLog ||
    !registeredLog.topics[1]
) {

    throw new Error(
        "ERC-8004 Registered event was not observed."
    );

}


const agentId =
    BigInt(
        registeredLog.topics[1]
    );


/*
 * Participant B:
 *
 * Use ABI + bytecode generated by participant B's own pinned
 * toolchain, but deploy into the SAME runtime used above.
 */

const deploy8060Hash =
    await owner.deployContract(
        {
            abi:
                artifact8060.abi,

            bytecode:
                artifact8060.bytecode
        }
    );


const deploy8060Receipt =
    await publicClient
        .waitForTransactionReceipt(
            {
                hash:
                    deploy8060Hash
            }
        );


if (
    !deploy8060Receipt.contractAddress
) {

    throw new Error(
        "ERC-8060 deployment produced no contract address."
    );

}


const erc8060 =
    getContract(
        {
            address:
                deploy8060Receipt.contractAddress,

            abi:
                artifact8060.abi,

            client: {
                public:
                    publicClient,

                wallet:
                    owner
            }
        }
    );


const mintPrice =
    await erc8060
        .read
        .MINT_PRICE();


const redeemValue =
    await erc8060
        .read
        .REDEEM_VALUE();


const mintPriceConstraint =
    requirement ===
        null
        ? null
        : (() => {

            const matches =
                requirement.constraints.filter(
                    constraint =>
                        constraint.participantSide ===
                            "B" &&
                        constraint.basis ===
                            "SOLIDITY_REQUIRE_STATEMENT" &&
                        typeof constraint.rawText ===
                            "string" &&
                        constraint.rawText.includes(
                            "msg.value"
                        ) &&
                        constraint.rawText.includes(
                            "MINT_PRICE"
                        )
                );


            if (
                matches.length !==
                1
            ) {

                throw new Error(
                    "Expected exactly one discovered ERC-8060 exact mint-price constraint."
                );

            }


            return matches[0];

        })();


const uriB =
    "ipfs://oecl/control/erc8060-value";


const txB =
    await erc8060
        .write
        .mint(
            [
                uriB
            ],
            {
                value:
                    mintPrice
            }
        );


const receiptB =
    await publicClient
        .waitForTransactionReceipt(
            {
                hash:
                    txB
            }
        );


let incorrectMintPriceRevertReasonConfirmed =
    false;


if (
    mintPriceConstraint !==
    null
) {

    const incorrectMintPrice =
        mintPrice +
        1n;


    try {

        await publicClient
            .simulateContract(
                {
                    address:
                        deploy8060Receipt.contractAddress,

                    abi:
                        artifact8060.abi,

                    functionName:
                        "mint",

                    args: [
                        "ipfs://oecl/control/erc8060-invalid-price"
                    ],

                    account:
                        owner.account,

                    value:
                        incorrectMintPrice
                }
            );

    } catch (error) {

        const errorText =
            [
                String(error),

                String(
                    error?.shortMessage ??
                    ""
                ),

                String(
                    error?.details ??
                    ""
                ),

                String(
                    error?.cause ??
                    ""
                ),

                String(
                    error?.cause?.shortMessage ??
                    ""
                ),

                String(
                    error?.cause?.details ??
                    ""
                ),

                String(
                    error?.cause?.reason ??
                    ""
                )
            ].join(
                "\n"
            );


        incorrectMintPriceRevertReasonConfirmed =
            errorText.includes(
                "Incorrect ETH amount"
            );


        if (
            !incorrectMintPriceRevertReasonConfirmed
        ) {

            throw error;

        }

    }


    if (
        !incorrectMintPriceRevertReasonConfirmed
    ) {

        throw new Error(
            "ERC-8060 incorrect mint-price counterfactual did not revert with the observed guard reason."
        );

    }

}


/*
 * Shared-foundation probe.
 *
 * This ABI deliberately knows only the ERC-721 surface.
 */

const erc721ProbeAbi = [

    {
        type:
            "function",

        name:
            "ownerOf",

        stateMutability:
            "view",

        inputs: [
            {
                name:
                    "tokenId",

                type:
                    "uint256"
            }
        ],

        outputs: [
            {
                name:
                    "",

                type:
                    "address"
            }
        ]
    },

    {
        type:
            "function",

        name:
            "tokenURI",

        stateMutability:
            "view",

        inputs: [
            {
                name:
                    "tokenId",

                type:
                    "uint256"
            }
        ],

        outputs: [
            {
                name:
                    "",

                type:
                    "string"
            }
        ]
    },

    {
        type:
            "function",

        name:
            "supportsInterface",

        stateMutability:
            "view",

        inputs: [
            {
                name:
                    "interfaceId",

                type:
                    "bytes4"
            }
        ],

        outputs: [
            {
                name:
                    "",

                type:
                    "bool"
            }
        ]
    }

];


const erc721A =
    getContract(
        {
            address:
                proxy.address,

            abi:
                erc721ProbeAbi,

            client:
                publicClient
        }
    );


const erc721B =
    getContract(
        {
            address:
                deploy8060Receipt.contractAddress,

            abi:
                erc721ProbeAbi,

            client:
                publicClient
        }
    );


const [
    ownerA,
    ownerB,
    tokenUriA,
    tokenUriB,
    supports721A,
    supports721B,
    valueB
] =
    await Promise.all(
        [
            erc721A.read.ownerOf(
                [
                    agentId
                ]
            ),

            erc721B.read.ownerOf(
                [
                    1n
                ]
            ),

            erc721A.read.tokenURI(
                [
                    agentId
                ]
            ),

            erc721B.read.tokenURI(
                [
                    1n
                ]
            ),

            erc721A.read.supportsInterface(
                [
                    "0x80ac58cd"
                ]
            ),

            erc721B.read.supportsInterface(
                [
                    "0x80ac58cd"
                ]
            ),

            erc8060.read.valueOf(
                [
                    1n
                ]
            )
        ]
    );


const ownerAddress =
    owner.account.address
        .toLowerCase();


const assertions = {

    participantATransactionMined:
        receiptA.status ===
        "success",

    participantBTransactionMined:
        receiptB.status ===
        "success",

    participantAOwnerPreserved:
        ownerA.toLowerCase() ===
        ownerAddress,

    participantBOwnerPreserved:
        ownerB.toLowerCase() ===
        ownerAddress,

    participantATokenUriPreserved:
        tokenUriA ===
        uriA,

    participantBTokenUriPreserved:
        tokenUriB ===
        uriB,

    participantAExposesERC721:
        supports721A ===
        true,

    participantBExposesERC721:
        supports721B ===
        true,

    participantBValuePreserved:
        valueB ===
        redeemValue

};


const passed =
    Object.values(
        assertions
    ).every(
        value =>
            value ===
            true
    );


if (
    !passed
) {

    throw new Error(
        "Shared ERC-721 foundation probe failed: " +
        JSON.stringify(
            assertions
        )
    );

}


const constraintObservations =
    mintPriceConstraint ===
        null
        ? []
        : [

            {
                observationId:
                    (
                        "REAL-CONTROL-MINT-PRICE-" +
                        mintPriceConstraint.constraintId
                    ),

                candidateId:
                    mintPriceConstraint.candidateId,

                constraintId:
                    mintPriceConstraint.constraintId,

                participantSide:
                    mintPriceConstraint.participantSide,

                verdict:
                    "PRESERVED",

                evidence: [
                    (
                        "ERC8060_EXACT_MINT_PRICE_ACCEPTED_TX:" +
                        txB
                    ),
                    "ERC8060_INCORRECT_MINT_PRICE_REVERT_REASON_CONFIRMED:Incorrect ETH amount"
                ]
            }

        ];


const report = {

    executionKind:
        "OECL_REAL_ERC8004_ERC8060_BILATERAL_CONTROL",

    chainId,

    sharedRuntime:
        true,

    participantA: {

        executed:
            true,

        contractAddresses: [
            proxy.address,
            realImpl.address
        ],

        transactionHashes: [
            txA
        ]

    },

    participantB: {

        executed:
            true,

        contractAddresses: [
            deploy8060Receipt.contractAddress
        ],

        transactionHashes: [
            deploy8060Hash,
            txB
        ]

    },

    observations: [
        "REAL_ERC8004_TRANSACTION_OBSERVED",
        "REAL_ERC8060_TRANSACTION_OBSERVED",
        "SAME_EVM_BILATERAL_EXECUTION_OBSERVED",
        "ERC721_SHARED_FOUNDATION_PROBE_PASSED",
        "ERC8060_REDEEMABLE_VALUE_PRESERVED"
    ],

    constraintObservations,

    scientificPolarity:
        "NEUTRAL",

    conclusion:
        "BILATERAL_EXECUTION_OBSERVED_WITHOUT_COMPOSITION_POLARITY"

};


console.log(
    "OECL_JOINT_EXECUTION_RESULT=" +
    JSON.stringify(
        report
    )
);
`;


export function
buildErc8004Erc8060ControlRecipe():
    ScientificJointContractHarnessRecipe {

    const npmCommand =
        process.platform ===
        "win32"
            ? "npm.cmd"
            : "npm";


    const hardhatCommand =
        process.platform ===
        "win32"
            ? ".\\node_modules\\.bin\\hardhat.cmd"
            : "./node_modules/.bin/hardhat";


    return {

        recipeId:
            "REAL-CONTROL-ERC8004-ERC8060-SHARED-ERC721",

        preparationSteps: [

            {
                stepId:
                    "ERC8004-INSTALL-PINNED-DEPENDENCIES",

                participantSide:
                    "A",

                command:
                    npmCommand,

                args: [
                    "ci",
                    "--legacy-peer-deps"
                ]
            },

            {
                stepId:
                    "ERC8004-COMPILE-PINNED-SOURCES",

                participantSide:
                    "A",

                command:
                    hardhatCommand,

                args: [
                    "compile"
                ],

                env: {

                    SEPOLIA_RPC_URL:
                        "http://127.0.0.1:8545",

                    MAINNET_RPC_URL:
                        "http://127.0.0.1:8545"

                }
            },

            {
                stepId:
                    "ERC8060-INSTALL-PINNED-DEPENDENCIES",

                participantSide:
                    "B",

                command:
                    npmCommand,

                args: [
                    "ci"
                ]
            },

            {
                stepId:
                    "ERC8060-COMPILE-PINNED-SOURCES",

                participantSide:
                    "B",

                command:
                    npmCommand,

                args: [
                    "run",
                    "compile"
                ]
            }

        ],

        driver: {

            participantSide:
                "A",

            fileName:
                "erc8004-erc8060-real-control.mjs",

            source:
                DRIVER_SOURCE,

            /*
             * Importing Hardhat inside the real driver causes the
             * participant A configuration to be validated again.
             *
             * These ephemeral local URLs satisfy configuration
             * validation only. The joint driver executes against the
             * in-process Hardhat simulated network and does not use
             * these endpoints as scientific evidence.
             */
            env: {

                SEPOLIA_RPC_URL:
                    "http://127.0.0.1:8545",

                MAINNET_RPC_URL:
                    "http://127.0.0.1:8545"

            }

        }

    };

}
