export enum ResearchFindingType {

    PROTOCOL_CLUSTER = "PROTOCOL_CLUSTER",

    CAPABILITY_CLUSTER = "CAPABILITY_CLUSTER",

    SOURCE_CLAIM = "SOURCE_CLAIM",

    COMPOSITION_CANDIDATE = "COMPOSITION_CANDIDATE"

}