export const SCIENTIFIC_COMPOSITION_VALUE_RULE_IDS = {

    CROSS_PROTOCOL_FUNCTIONAL_COMPLEMENT:
        "VALUE-RULE-001",

    COMPLETE_OBJECTIVE_COVERAGE:
        "VALUE-RULE-002",

    DISTRIBUTED_OBJECTIVE_COVERAGE:
        "VALUE-RULE-003",

    STRICT_SUBSET_ONLY:
        "VALUE-RULE-004"

} as const;


export type ScientificCompositionValueRuleId =
    typeof SCIENTIFIC_COMPOSITION_VALUE_RULE_IDS[
        keyof typeof SCIENTIFIC_COMPOSITION_VALUE_RULE_IDS
    ];