export type ScientificPostExecutionReferentialIntegrityStatus =
    | "VALID"

    | "CAMPAIGN_MISMATCH"

    | "BROKEN_FEEDBACK_EVIDENCE_REFERENCE"
    | "FEEDBACK_EVIDENCE_PROVENANCE_MISMATCH"

    | "BROKEN_MATCH_FEEDBACK_REFERENCE"
    | "MATCH_FEEDBACK_PROVENANCE_MISMATCH"

    | "BROKEN_ASSIMILATION_MATCH_REFERENCE"
    | "AMBIGUOUS_ASSIMILATION_MATCH_REFERENCE"
    | "ASSIMILATION_MATCH_PROVENANCE_MISMATCH"

    | "BROKEN_RECONCILIATION_ASSIMILATION_REFERENCE"
    | "AMBIGUOUS_RECONCILIATION_KNOWLEDGE_REFERENCE"
    | "RECONCILIATION_EVIDENCE_PRESSURE_MISMATCH"

    | "BROKEN_REVISION_RECONCILIATION_REFERENCE"
    | "AMBIGUOUS_REVISION_RECONCILIATION_REFERENCE"
    | "REVISION_RECONCILIATION_MISMATCH"

    | "BROKEN_AUTHORIZATION_REVISION_REFERENCE"
    | "AMBIGUOUS_AUTHORIZATION_REVISION_REFERENCE"
    | "AUTHORIZATION_REVISION_MISMATCH"

    | "BROKEN_TRANSITION_AUTHORIZATION_REFERENCE"
    | "AMBIGUOUS_TRANSITION_AUTHORIZATION_REFERENCE"
    | "TRANSITION_AUTHORIZATION_MISMATCH";


export interface ScientificPostExecutionReferentialIntegrityIssue {

    status:
        ScientificPostExecutionReferentialIntegrityStatus;

    entityType:
        | "EVIDENCE"
        | "FEEDBACK"
        | "MATCH"
        | "ASSIMILATION"
        | "RECONCILIATION"
        | "REVISION"
        | "AUTHORIZATION"
        | "TRANSITION";

    entityId: string;

    referenceType: string;

    referenceId:
        string | null;

    explanation: string;
}